import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Bottombar from '@/components/shared/Bottombar';
import Header from '@/components/shared/Header';
import Leftbar from '@/components/shared/Leftbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="main_container">
          <Leftbar />
          <div className="flex flex-col flex-1 min-h-0">
            <Header />
            {/* <LoadingBar /> */}
            {/* Loading logic */}
            {children}
          </div>
          <Bottombar />
        </section>
      </body>
    </html>
  );
}
